services:
  api_server:
    container_name: pinnacle-play-api_server
    build:
      context: ./api_server/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api_server:/app 
    depends_on:
      - db
  web_front:
    container_name: pinnacle-play-web_front
    build:
      context: ./web_front/
      dockerfile: Dockerfile
    volumes:
      - ./web_front:/app
    ports:
      - 8080:8080 
  db:
    container_name: pinnacle-play-db
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
